name: Problem Report
description: Submit a real enterprise data analysis task where AI failed (essence-level only; no data)
title: "[PROBLEM] <short business ask>"
labels: ["type: problem", "needs: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please **do not include any proprietary data or PII**.
        We only need enough *business context and shape* so UCB can recreate a representative case internally.

  - type: input
    id: business-question
    attributes:
      label: Business question (exact ask)
      description: The question you needed answered.
      placeholder: e.g., Calculate churn from Salesforce + product usage for Q3 FY2024 (FY starts July)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category (select all that apply)
      multiple: true
      options:
        - Single-Source SQL
        - Cross-Source Federation
        - Integrating Unstructured Data
        - Production-Grade Control Flow
        - Business Term Disambiguation
        - Temporal, Unit & Currency-Aware (incl. SCD)
        - Entity Resolution
        - Time-Series, Cohorts & Funnels
        - External APIs/SaaS/Open-Web
        - Governance & Compliance
        - Advanced Analytics (Stats/Graph)
        - Implicit Relationship Discovery
        - Other/Unsure
    validations:
      required: true

  - type: textarea
    id: time
    attributes:
      label: Time window & calendars
      description: Time bounds, business/fiscal calendars, timezone, late-arriving data.
      placeholder: |
        e.g., Q3 FY2024 (FY starts July), timezone UTC; late events up to T+3 days
    validations:
      required: true

  - type: textarea
    id: sources
    attributes:
      label: Data sources & backends (no data; just names)
      description: Systems and objects involved, approx. sizes, and freshness.
      placeholder: |
        Example:
        - Salesforce: objects=Account, Opportunity (500k rows), refreshed hourly
        - Snowflake: schema=product, tables=events, sessions (~10M rows/day)
        - Stripe: charges, subscriptions (API)
    validations:
      required: true

  - type: textarea
    id: entities
    attributes:
      label: Entities & identifiers
      description: Primary entities and IDs, and which system is source of truth.
      placeholder: |
        Example:
        - Entities: account, user
        - Identifiers: salesforce.account_id, product.user_id, billing.account_uuid
        - Source of truth: ARR from Stripe; account hierarchy from Salesforce
    validations:
      required: true

  - type: textarea
    id: joins
    attributes:
      label: Join logic & business rules
      description: How sources should be stitched; exclusions; precedence rules.
      placeholder: |
        Example:
        - Join users → accounts by account_uuid; prefer Stripe over Salesforce on conflicts
        - Exclude internal/test accounts where account.tier = 'internal' or email like '%@yourco.com'
        - Treat cancelled orders as non-active; define "active" as ≥1 revenue-generating action / 30 days
    validations:
      required: true

  - type: textarea
    id: expected-shape
    attributes:
      label: Expected output shape (columns, types, grain)
      description: The *shape* you expect back. No actual data required.
      render: markdown
      placeholder: |
        grain: account_id x fiscal_quarter
        columns:
          - account_id: string (PK)
          - fiscal_quarter: string (e.g., FY2024-Q3)
          - churned: boolean
          - churn_reason: enum [non-payment, cancellation, downgrade]
          - arr_usd: number
    validations:
      required: true

  - type: textarea
    id: tools
    attributes:
      label: Tools/approach attempted
      description: LLM(s), agents, semantic layer, tool selection, any prompts/settings that matter.
      placeholder: |
        e.g., GPT-4o + function calling; LangChain SQL agent (PG + SF tools); dbt semantic layer v1.7
    validations:
      required: true

  - type: textarea
    id: failure
    attributes:
      label: Failure mode (be specific)
      description: What went wrong and how you knew; include wrong SQL/plan snippets if possible.
      placeholder: |
        1) Used calendar quarter vs fiscal quarter
        2) Joined on company name → false matches ('Acme')
        3) Ignored SCD2; used current territory instead of historical as-of
    validations:
      required: true

  - type: dropdown
    id: scale
    attributes:
      label: Scale (approximate)
      options:
        - ≤100k rows
        - 100k–10M rows
        - 10M–1B rows
        - ">1B rows"
    validations:
      required: false

  - type: textarea
    id: policies
    attributes:
      label: Policy/constraints (optional)
      description: RLS, masking, k-min, contract/policy docs that define rules (no uploads—just describe).
      placeholder: |
        Example: RLS by region; salary metrics require k>=5; FX by txn timestamp from ECB rates
    validations:
      required: false

  - type: checkboxes
    id: agreements
    attributes:
      label: Contribution agreement
      options:
        - label: I confirm this submission contains **no proprietary data or secrets**
          required: true
        - label: I agree this problem can be used in the public benchmark
          required: true
