name: Technique Submission
description: Submit a technique/approach to test on the benchmark
title: "[TECHNIQUE] <name>"
labels: ["type: technique", "needs: triage"]
body:
  - type: input
    id: technique-name
    attributes:
      label: Technique name
      placeholder: e.g., Semantic Layer + LLM with dbt metrics
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary (how it works)
      description: The core idea in 3–6 bullets.
      placeholder: |
        - LLM queries metrics via semantic layer APIs; no direct SQL generation
        - Tooling enforces business calendars and SCD2
        - Deterministic retries + caching for external APIs
    validations:
      required: true

  - type: dropdown
    id: applies-to
    attributes:
      label: Where it applies (select all)
      multiple: true
      options:
        - Single-Source SQL
        - Cross-Source Federation
        - Integrating Unstructured Data
        - Production-Grade Control Flow
        - Business Term Disambiguation
        - Temporal, Unit & Currency-Aware (incl. SCD)
        - Entity Resolution
        - Time-Series, Cohorts & Funnels
        - External APIs/SaaS/Open-Web
        - Governance & Compliance
        - Advanced Analytics (Stats/Graph)
        - Implicit Relationship Discovery
    validations:
      required: true

  - type: textarea
    id: io-contract
    attributes:
      label: Input/Output contract
      description: What metadata or components must exist? What does it return?
      placeholder: |
        Requires: dbt semantic layer, metrics YAML, SLA policy doc store.
        Returns: SQL or metric results with citations to applied policies.
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: Dependencies & environment
      description: Libraries/services, dialects, data engines; any version constraints.
      placeholder: |
        dbt=1.7+, Snowflake/BigQuery, OpenAI function calling, Redis cache
    validations:
      required: false

  - type: textarea
    id: evaluation
    attributes:
      label: Observed results / claims
      description: Any empirical results, wins/failures, or expected tradeoffs.
      placeholder: |
        On ~200 internal queries, 90% accuracy on standard metrics; weaker on exploratory tasks.
    validations:
      required: false

  - type: textarea
    id: limits
    attributes:
      label: Known limitations
      description: Where it struggles or is out of scope.
      placeholder: |
        Requires well-defined metrics; cross-metric math with different grains is tricky.
    validations:
      required: false

  - type: checkboxes
    id: agreements
    attributes:
      label: Contribution agreement
      options:
        - label: I confirm this submission contains **no proprietary data or secrets**
          required: true
        - label: I agree this technique can be tested and results shared publicly
          required: true
